INSERT INTO permissions (permission_key, module, description)
				VALUES
					('users.invite',   'users', 'Invite team members to the organization'),
					('rbac.manage',    'rbac',  'Create and manage roles and permissions'),
					('apikeys.manage', 'apikeys', 'Generate and revoke API keys'),
					('billing.manage', 'billing', 'Manage subscriptions and billing'),
					('users.manage',  'users',  'Manage organization members (update role, deactivate)'),
					('crm.leads.write',  'crm',  'Create and manage CRM leads'),
					('crm.quotes.write', 'crm',  'Manage and analyze CRM quotes'),
					('crm.tickets.write', 'crm',  'Create and manage CRM support tickets'),
					('accounting.ledger.write',   'accounting', 'Post general ledger journal entries'),
					('accounting.invoices.write', 'accounting', 'Upload and process invoices'),
					('expenses.submit',           'accounting', 'Submit expense reports'),
					('fleet.telematics.ingest',   'fleet',     'Ingest vehicle telemetry data via API key'),
					('fleet.routes.manage',       'fleet',     'Generate and manage optimized fleet routes'),
					('inventory.read',            'inventory', 'Read inventory reorder predictions and stock levels'),
					('hr.attendance.write',       'hr',        'Clock in/out and manage attendance records'),
					('hr.recruitment.write',      'hr',        'Parse resumes and manage job applications'),
					('knowledge.read',            'knowledge', 'Search and read knowledge base documents'),
					('copilot.use',               'platform',  'Use the AI text-to-SQL copilot query feature'),
					('workflows.execute',         'platform',  'Trigger and execute low-code automated workflows'),
					('security.audit.read',       'platform',  'Read security audit anomaly logs'),
					('crm.fieldvisits.write',     'crm',       'Schedule and manage field sales visits'),
					('crm.campaigns.write',       'crm',       'Create and manage marketing campaigns'),
					('accounting.assets.write',    'accounting', 'Register and manage fixed assets'),
					('accounting.assets.read',     'accounting', 'View fixed assets and depreciation'),
					('accounting.tax.manage',      'accounting', 'Create and manage tax rates'),
					('accounting.tax.read',        'accounting', 'Calculate and view tax computations'),
					('accounting.bankrec.write',   'accounting', 'Import bank statements and run reconciliation'),
					('accounting.exchangerates.write', 'accounting', 'Set and manage currency exchange rates'),
					('accounting.currencyconvert.read', 'accounting', 'Convert amounts between currencies'),
					('hr.employees.write',         'hr',        'Create and update employee records'),
					('hr.employees.read',          'hr',        'View employee records'),
					('hr.payroll.write',           'hr',        'Run payroll and manage payroll records'),
					('hr.payroll.read',            'hr',        'View payroll runs and history'),
					('hr.shifts.write',            'hr',        'Create shift templates and assignments'),
					('hr.shifts.read',             'hr',        'View shift schedules and predictions'),
					('hr.attendance.clockout',     'hr',        'Clock out and complete attendance records'),
					('inventory.receive',          'inventory', 'Receive stock into warehouses'),
					('inventory.issue',            'inventory', 'Issue stock from warehouses'),
					('inventory.transfer',         'inventory', 'Transfer stock between warehouses'),
					('inventory.snapshot',         'inventory', 'View current inventory levels'),
					('bi.dashboards.write',        'platform',  'Create and manage BI executive dashboards'),
					('bi.dashboards.read',         'platform',  'View BI executive dashboards'),
					('iot.devices.write',          'platform',  'Register and manage IoT devices'),
					('iot.readings.ingest',        'platform',  'Ingest IoT device readings'),
					('manufacturing.boms.write',   'manufacturing', 'Create and manage bills of materials'),
					('manufacturing.workorders.write', 'manufacturing', 'Create and manage work orders'),
					('procurement.po.write',       'procurement', 'Create and manage purchase orders'),
					('procurement.supplier.read',  'procurement', 'View supplier risk reports')
				ON CONFLICT (permission_key) DO NOTHING
